### ISSUE TITLE
Supabase Demo Not Working

### ISSUE THREAD

**Issue by mcmah309** [powersync-ja/self-host-demo#24]
I tried to setup the supabase demo following the steps here https://github.com/powersync-ja/self-host-demo/tree/main/demos/supabase

But I ran into a few errors. Most notably this in the logs
```
powersync-1      | {"cause":{"code":"ENOTFOUND","errno":-3008,"hostname":"host.docker.internal","syscall":"getaddrinfo"},"level":"error","message":"Replication error getaddrinfo ENOTFOUND host.docker.internal","name":"PgError","stack":"PgError: getaddrinfo ENOTFOUND host.docker.internal\n    at PgConnection.start (file:///app/node_modules/.pnpm/pgwire@https+++codeload.github.com+kagis+pgwire+tar.gz+f1cb95f9a0f42a612bb5a6b67bb2eb793fc5fc87/node_modules/pgwire/mod.js:270:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Module.pgconnect (file:///app/node_modules/.pnpm/pgwire@https+++codeload.github.com+kagis+pgwire+tar.gz+f1cb95f9a0f42a612bb5a6b67bb2eb793fc5fc87/node_modules/pgwire/mod.js:28:3)\n    at async Module.pgconnect (file:///app/packages/jpgwire/dist/pgwire.js:8:12)\n    at async Module.connectPgWire (file:///app/packages/jpgwire/dist/util.js:72:24)\n    at async PgManager.replicationConnection (file:///app/packages/service-core/dist/util/PgManager.js:16:16)\n    at async WalStream.replicate (file:///app/packages/service-core/dist/replication/WalStream.js:428:43)\n    at async WalStreamRunner.replicateOnce (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:72:13)\n    at async WalStreamRunner.replicateLoop (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:45:13)\n    at async WalStreamRunner.run (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:23:13)","timestamp":"2024-08-01T19:04:25.808Z"}
powersync-1      | {"code":"ENOTFOUND","errno":-3008,"hostname":"host.docker.internal","level":"error","message":"cause getaddrinfo ENOTFOUND host.docker.internal","stack":"Error: getaddrinfo ENOTFOUND host.docker.internal\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)","syscall":"getaddrinfo","timestamp":"2024-08-01T19:04:25.808Z"}
powersync-1      | {"cause":{"code":"ENOTFOUND","errno":-3008,"hostname":"host.docker.internal","syscall":"getaddrinfo"},"level":"error","message":"Replication failed on powersync_1_58c1 getaddrinfo ENOTFOUND host.docker.internal","name":"PgError","stack":"PgError: getaddrinfo ENOTFOUND host.docker.internal\n    at PgConnection.start (file:///app/node_modules/.pnpm/pgwire@https+++codeload.github.com+kagis+pgwire+tar.gz+f1cb95f9a0f42a612bb5a6b67bb2eb793fc5fc87/node_modules/pgwire/mod.js:270:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Module.pgconnect (file:///app/node_modules/.pnpm/pgwire@https+++codeload.github.com+kagis+pgwire+tar.gz+f1cb95f9a0f42a612bb5a6b67bb2eb793fc5fc87/node_modules/pgwire/mod.js:28:3)\n    at async Module.pgconnect (file:///app/packages/jpgwire/dist/pgwire.js:8:12)\n    at async Module.connectPgWire (file:///app/packages/jpgwire/dist/util.js:72:24)\n    at async PgManager.replicationConnection (file:///app/packages/service-core/dist/util/PgManager.js:16:16)\n    at async WalStream.replicate (file:///app/packages/service-core/dist/replication/WalStream.js:428:43)\n    at async WalStreamRunner.replicateOnce (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:72:13)\n    at async WalStreamRunner.replicateLoop (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:45:13)\n    at async WalStreamRunner.run (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:23:13)","timestamp":"2024-08-01T19:04:25.809Z"}
```

And http://localhost:4170/ just serves a blank black screen.

Note: Making the `.env` configuration changes needed for https://github.com/powersync-ja/self-host-demo/issues/25 still results in the same type of error.

**Comment by stevensJourney** [comment]
What operating system are you using to run the demo? I see Linux has some extra steps required in order to access `host.docker.internal` - [refference](https://stackoverflow.com/questions/48546124/what-is-the-linux-equivalent-of-host-docker-internal).

We currently use `host.docker.internal` to access the Supabase Postgres connection from the PowerSync Docker container. There might be better ways for us to access this.

**Comment by mcmah309** [comment]
I am using linux. Adding to the compose file
```yaml
extra_hosts:
      - "host.docker.internal:host-gateway"
```
or directly adding
```env
PG_DATABASE_HOSTNAME=172.17.0.1
```
Has no effect on the outcome, but you can tell by the error messages that it is being used.
```
powersync-1      | {"cause":{"address":"172.17.0.1","code":"ECONNREFUSED","errno":-111,"port":5433,"syscall":"connect"},"level":"error","message":"Replication error connect ECONNREFUSED 172.17.0.1:5433","name":"PgError","stack":"PgError: connect ECONNREFUSED 172.17.0.1:5433\n    at PgConnection.start (file:///app/node_modules/.pnpm/pgwire@https+++codeload.github.com+kagis+pgwire+tar.gz+f1cb95f9a0f42a612bb5a6b67bb2eb793fc5fc87/node_modules/pgwire/mod.js:270:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Module.pgconnect (file:///app/node_modules/.pnpm/pgwire@https+++codeload.github.com+kagis+pgwire+tar.gz+f1cb95f9a0f42a612bb5a6b67bb2eb793fc5fc87/node_modules/pgwire/mod.js:28:3)\n    at async Module.pgconnect (file:///app/packages/jpgwire/dist/pgwire.js:8:12)\n    at async Module.connectPgWire (file:///app/packages/jpgwire/dist/util.js:72:24)\n    at async PgManager.replicationConnection (file:///app/packages/service-core/dist/util/PgManager.js:16:16)\n    at async WalStream.replicate (file:///app/packages/service-core/dist/replication/WalStream.js:428:43)\n    at async WalStreamRunner.replicateOnce (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:72:13)\n    at async WalStreamRunner.replicateLoop (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:45:13)\n    at async WalStreamRunner.run (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:23:13)","timestamp":"2024-08-02T12:50:03.475Z"}
powersync-1      | {"address":"172.17.0.1","code":"ECONNREFUSED","errno":-111,"level":"error","message":"cause connect ECONNREFUSED 172.17.0.1:5433","port":5433,"stack":"Error: connect ECONNREFUSED 172.17.0.1:5433\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)","syscall":"connect","timestamp":"2024-08-02T12:50:03.475Z"}
powersync-1      | {"cause":{"address":"172.17.0.1","code":"ECONNREFUSED","errno":-111,"port":5433,"syscall":"connect"},"level":"error","message":"Replication failed on powersync_1_58c1 connect ECONNREFUSED 172.17.0.1:5433","name":"PgError","stack":"PgError: connect ECONNREFUSED 172.17.0.1:5433\n    at PgConnection.start (file:///app/node_modules/.pnpm/pgwire@https+++codeload.github.com+kagis+pgwire+tar.gz+f1cb95f9a0f42a612bb5a6b67bb2eb793fc5fc87/node_modules/pgwire/mod.js:270:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Module.pgconnect (file:///app/node_modules/.pnpm/pgwire@https+++codeload.github.com+kagis+pgwire+tar.gz+f1cb95f9a0f42a612bb5a6b67bb2eb793fc5fc87/node_modules/pgwire/mod.js:28:3)\n    at async Module.pgconnect (file:///app/packages/jpgwire/dist/pgwire.js:8:12)\n    at async Module.connectPgWire (file:///app/packages/jpgwire/dist/util.js:72:24)\n    at async PgManager.replicationConnection (file:///app/packages/service-core/dist/util/PgManager.js:16:16)\n    at async WalStream.replicate (file:///app/packages/service-core/dist/replication/WalStream.js:428:43)\n    at async WalStreamRunner.replicateOnce (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:72:13)\n    at async WalStreamRunner.replicateLoop (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:45:13)\n    at async WalStreamRunner.run (file:///app/packages/service-core/dist/replication/WalStreamRunner.js:23:13)","timestamp":"2024-08-02T12:50:03.476Z"}
```

**Comment by kobiebotha** [comment]
Closing due to inactivity and seems resolved based on comments in https://github.com/powersync-ja/self-host-demo/issues/25
